### ISSUE TITLE
related discussion / other interested stakeholders

### ISSUE THREAD

**Issue by kjappelbaum** [TheELNConsortium/.github#1]
Hello @SteffenBrinckmann 

you might have seen https://github.com/MADICES/MADICES-2022/discussions/35 that came out of a recent workshop. 
I guess it would make a lot of sense to align efforts. 

Cheers,
Kevin

**Comment by NicolasCARPi** [comment]
I agree that the goals align and that we should work together. It's great that you can join us for our first meeting.
