### ISSUE TITLE
interest in the activity of the group

### ISSUE THREAD

**Issue by djeanner** [TheELNConsortium/.github#2]
Hi,
I'm interested in the activity of this group. Can you take me in?
Damien

**Comment by NicolasCARPi** [comment]
Hello Damien,

An invitation has been sent. You should subscribe to notifications from https://github.com/TheELNConsortium/TheELNFileFormat and https://github.com/TheELNConsortium/Discussions-And-Future-Topics.

The second repository linked would be a good place to start a discussion about a topic of your choice related to ELNs and data management.

Best,
~Nicolas
